name: skill_tree
description: A package for creating skill trees of any shape and size
version: 0.0.1-nullsafety.0
homepage: https://github.com/Nolence/skill_tree

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
